spring.application.name=auth-service
server.port=8084

management.endpoints.web.exposure.include=health,info

# autenticacion (para cualquier endpoint futuro que requiera un JWT valido)
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8180/realms/HireFlow-system

keycloak.server-url=http://localhost:8180
keycloak.realm=HireFlow-system

# Service Account (HireFlow-admin-client): usado para crear usuarios y asignar roles
keycloak.admin-client-id=HireFlow-admin-client
keycloak.admin-client-secret=${KEYCLOAK_ADMIN_CLIENT_SECRET}

# Cliente publico (HireFlow-app): usado para el login (password grant)
keycloak.public-client-id=HireFlow-app
keycloak.public-client-secret=${KEYCLOAK_APP_CLIENT_SECRET}
