spring.application.name=match-service
server.port=8082

spring.datasource.url=jdbc:postgresql://localhost:5434/match_db
spring.datasource.username=postgres
spring.datasource.password=Uisrael.
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
management.endpoints.web.exposure.include=health,info

#URL DE otros servicios
candidato.service.url=http://candidato-service:8081
vacante.service.url=http://vacante-service:8083
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent
#gemini.api.key=AQUI_PONDRAS_TU_LLAVE_DE_GOOGLE

# Resilience4j - Circuit Breaker para WebClients (Candidatos y Vacantes)
resilience4j.circuitbreaker.instances.externalServices.sliding-window-size=5
resilience4j.circuitbreaker.instances.externalServices.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.externalServices.wait-duration-in-open-state=15s
resilience4j.circuitbreaker.instances.externalServices.permitted-number-of-calls-in-half-open-state=3

# Resilience4j - Retry para WebClients
resilience4j.retry.instances.externalServices.max-attempts=3
resilience4j.retry.instances.externalServices.wait-duration=2s

# Resilience4j - Timeout
resilience4j.timelimiter.instances.externalServices.timeout-duration=15s

#autenticacion
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8180/realms/HireFlow-system



