events {
    worker_connections 1024;
}

http {

    upstream candidato-service {
        server candidato-service:8081;  # nombre del servicio en la red Docker
    }

    upstream match-service {
        server match-service:8082;
    }

    upstream vacante-service {
        server vacante-service:8083;
    }

    upstream auth-service {
        server auth-service:8084;
    }

    server {
        listen 80;

        location /api/v1/candidatos {
            proxy_pass http://candidato-service;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        location /api/v1/matches {
            proxy_pass http://match-service;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        location /api/v1/vacantes {
            proxy_pass http://vacante-service;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        location /api/auth {
            proxy_pass http://auth-service;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        location /health {
            return 200 '{"status":"UP","service":"api-gateway"}';
            add_header Content-Type application/json;
        }
    }
}
